-- Standard non-benchmark movement library additions.
-- These are exercises used for workout/program building; benchmark/test versions stay separate via show_on_leaderboard = true.

insert into public.strength_movements (movement_key, name, description, category, is_builtin, show_on_leaderboard)
values
  ('air-squat', 'Air Squat', 'Bodyweight squat movement.', 'strength', true, false),
  ('overhead-squat', 'Overhead Squat', 'Barbell overhead squat movement.', 'strength', true, false),
  ('thruster', 'Thruster', 'Front squat directly into an overhead press.', 'strength', true, false),
  ('sumo-deadlift-high-pull', 'Sumo Deadlift High Pull', 'Wide-stance deadlift into high pull.', 'strength', true, false),
  ('medicine-ball-clean', 'Medicine Ball Clean', 'Medicine ball clean from floor to front rack.', 'strength', true, false),
  ('wall-ball', 'Wall Ball', 'Medicine ball squat and throw to target.', 'wod', true, false),
  ('burpee', 'Burpee', 'Bodyweight burpee movement.', 'wod', true, false),
  ('box-jump-over', 'Box Jump Over', 'Jump over a box, landing or stepping down safely.', 'wod', true, false),
  ('box-step-up', 'Box Step-Up', 'Step-up onto a box or bench.', 'strength', true, false),
  ('walking-lunge', 'Walking Lunge', 'Alternating forward lunges while traveling.', 'strength', true, false),
  ('reverse-lunge', 'Reverse Lunge', 'Alternating lunges stepping backward.', 'strength', true, false),
  ('front-rack-lunge', 'Front Rack Lunge', 'Lunge with barbell or dumbbells in front rack.', 'strength', true, false),
  ('romanian-deadlift', 'Romanian Deadlift', 'Hip-hinge deadlift variation emphasizing hamstrings.', 'strength', true, false),
  ('good-morning', 'Good Morning', 'Hip hinge with barbell on back.', 'strength', true, false),
  ('hip-thrust', 'Hip Thrust', 'Glute bridge/hip extension loaded from the hips.', 'strength', true, false),
  ('glute-bridge', 'Glute Bridge', 'Supine hip extension movement.', 'strength', true, false),
  ('strict-pull-up', 'Strict Pull-Up', 'Strict bodyweight pull-up.', 'gymnastics', true, false),
  ('kipping-pull-up', 'Kipping Pull-Up', 'Kipping bodyweight pull-up.', 'gymnastics', true, false),
  ('chest-to-bar-pull-up', 'Chest-to-Bar Pull-Up', 'Pull-up with chest contact standard.', 'gymnastics', true, false),
  ('chin-up', 'Chin-Up', 'Supinated-grip pull-up.', 'gymnastics', true, false),
  ('toes-to-bar', 'Toes-to-Bar', 'Hanging gymnastics movement bringing toes to the bar.', 'gymnastics', true, false),
  ('knees-to-elbows', 'Knees-to-Elbows', 'Hanging gymnastics movement bringing knees to elbows.', 'gymnastics', true, false),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'Hanging core movement raising knees.', 'gymnastics', true, false),
  ('ghd-sit-up', 'GHD Sit-Up', 'Sit-up performed on a GHD.', 'gymnastics', true, false),
  ('abmat-sit-up', 'AbMat Sit-Up', 'Sit-up performed with AbMat support.', 'gymnastics', true, false),
  ('hollow-hold', 'Hollow Hold', 'Static hollow-body core hold.', 'gymnastics', true, false),
  ('plank', 'Plank', 'Static core plank hold.', 'gymnastics', true, false),
  ('dip', 'Dip', 'Bodyweight dip movement.', 'gymnastics', true, false),
  ('ring-dip', 'Ring Dip', 'Dip performed on gymnastic rings.', 'gymnastics', true, false),
  ('handstand-push-up', 'Handstand Push-Up', 'Inverted pressing gymnastics movement.', 'gymnastics', true, false),
  ('handstand-walk', 'Handstand Walk', 'Inverted walking gymnastics skill.', 'gymnastics', true, false),
  ('rope-climb', 'Rope Climb', 'Rope climb gymnastics movement.', 'gymnastics', true, false),
  ('muscle-up', 'Muscle-Up', 'Pull-up transition into dip over bar or rings.', 'gymnastics', true, false),
  ('ring-muscle-up', 'Ring Muscle-Up', 'Muscle-up performed on rings.', 'gymnastics', true, false),
  ('bar-muscle-up', 'Bar Muscle-Up', 'Muscle-up performed on a pull-up bar.', 'gymnastics', true, false),
  ('double-under', 'Double-Under', 'Jump rope skill with two rope passes per jump.', 'gymnastics', true, false),
  ('single-under', 'Single-Under', 'Jump rope skill with one rope pass per jump.', 'gymnastics', true, false),
  ('clean', 'Clean', 'Barbell clean from floor to front rack.', 'strength', true, false),
  ('hang-clean', 'Hang Clean', 'Clean variation starting from the hang.', 'strength', true, false),
  ('hang-power-clean', 'Hang Power Clean', 'Power clean variation starting from the hang.', 'strength', true, false),
  ('hang-squat-clean', 'Hang Squat Clean', 'Squat clean variation starting from the hang.', 'strength', true, false),
  ('jerk', 'Jerk', 'Overhead jerk movement.', 'strength', true, false),
  ('push-jerk', 'Push Jerk', 'Jerk variation with dip, drive, and catch.', 'strength', true, false),
  ('split-jerk', 'Split Jerk', 'Jerk variation caught in split stance.', 'strength', true, false),
  ('snatch', 'Snatch', 'Barbell snatch from floor to overhead.', 'strength', true, false),
  ('hang-snatch', 'Hang Snatch', 'Snatch variation starting from the hang.', 'strength', true, false),
  ('hang-power-snatch', 'Hang Power Snatch', 'Power snatch variation starting from the hang.', 'strength', true, false),
  ('hang-squat-snatch', 'Hang Squat Snatch', 'Squat snatch variation starting from the hang.', 'strength', true, false),
  ('snatch-balance', 'Snatch Balance', 'Overhead squat receiving drill from the back rack.', 'strength', true, false),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'Bench press performed with dumbbells.', 'strength', true, false),
  ('dumbbell-row', 'Dumbbell Row', 'Single-arm or double-arm dumbbell row.', 'strength', true, false),
  ('dumbbell-thruster', 'Dumbbell Thruster', 'Thruster performed with dumbbells.', 'strength', true, false),
  ('dumbbell-clean', 'Dumbbell Clean', 'Clean performed with dumbbells.', 'strength', true, false),
  ('dumbbell-snatch', 'Dumbbell Snatch', 'Snatch performed with a dumbbell.', 'strength', true, false),
  ('dumbbell-lunge', 'Dumbbell Lunge', 'Lunge performed with dumbbells.', 'strength', true, false),
  ('farmer-carry', 'Farmer Carry', 'Loaded carry with dumbbells, kettlebells, or handles.', 'strength', true, false),
  ('goblet-squat', 'Goblet Squat', 'Squat holding a kettlebell or dumbbell at chest.', 'strength', true, false),
  ('turkish-get-up', 'Turkish Get-Up', 'Ground-to-standing kettlebell movement.', 'strength', true, false),
  ('kettlebell-clean', 'Kettlebell Clean', 'Clean performed with a kettlebell.', 'strength', true, false),
  ('kettlebell-snatch', 'Kettlebell Snatch', 'Snatch performed with a kettlebell.', 'strength', true, false),
  ('kettlebell-press', 'Kettlebell Press', 'Strict press performed with a kettlebell.', 'strength', true, false),
  ('kettlebell-deadlift', 'Kettlebell Deadlift', 'Deadlift performed with a kettlebell.', 'strength', true, false),
  ('row', 'Row', 'Rowing machine movement.', 'cardio', true, false),
  ('run', 'Run', 'Running movement.', 'cardio', true, false),
  ('ski-erg', 'Ski Erg', 'Ski erg machine movement.', 'cardio', true, false),
  ('assault-bike', 'Assault Bike', 'Fan bike cardio movement.', 'cardio', true, false),
  ('echo-bike', 'Echo Bike', 'Rogue Echo Bike cardio movement.', 'cardio', true, false),
  ('bike-erg', 'Bike Erg', 'Bike erg cardio movement.', 'cardio', true, false),
  ('sled-push', 'Sled Push', 'Loaded sled push.', 'cardio', true, false),
  ('sled-pull', 'Sled Pull', 'Loaded sled pull or drag.', 'cardio', true, false),
  ('shuttle-run', 'Shuttle Run', 'Short-distance shuttle running movement.', 'cardio', true, false)
on conflict (movement_key) do nothing;
